name: DepthRegularizedGS
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - plyfile
  - python
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tqdm
  - opencv
  - pip:
    - viser
    - submodules/diff-gaussian-rasterization-depth
    - submodules/simple-knn
